// =============================================================================
// js_lexer.cpp - JavaScript Lexer Implementation
// =============================================================================
//
// TEACHING NOTE: Lexer Implementation Details
// ============================================
//
// The lexer is a hand-written state machine. We scan one character at a time
// and build up tokens. This is the approach used by most production compilers
// because table-driven lexers (generated by tools like flex/lex) are slower
// and harder to debug.
//
// Key challenges in lexing JavaScript:
//
// 1. Regex vs Division (/)
//    JavaScript uses / for both division and regex literals. The lexer must
//    decide based on context. After an expression-producing token (identifier,
//    literal, ), ]), / is division. After an operator, keyword, or at
//    statement start, / begins a regex.
//
// 2. Automatic Semicolon Insertion (ASI)
//    JavaScript automatically inserts semicolons at newlines in certain cases.
//    The rules are subtle:
//      - A semicolon is inserted before a newline if the next token cannot
//        continue the current statement
//      - A semicolon is inserted at the end of the file
//      - A semicolon is inserted before a closing brace
//    We handle ASI in the parser, not the lexer. The lexer just produces
//    newline-aware tokens.
//
// 3. Template Literals
//    Template literals can contain expressions: `hello ${name}!`
//    The lexer must track nesting and produce tokens that the parser can
//    use to build template AST nodes.
//
// 4. Numbers
//    JavaScript numbers are IEEE 754 doubles. We support:
//      - Decimal: 1, 1.5, .5, 1e10, 1.5e-3
//      - Hex: 0xFF, 0Xff
//      - Binary: 0b1010, 0B1010
//      - Octal: 0o777, 0O777
//      - BigInt: 123n (we store as string, not actual BigInt)
//
// How V8 lexer works:
// ===================
// V8 scanner (src/parsing/scanner.cc) is hand-written in C++. It uses:
//   - ASCII lookup tables for fast character classification
//   - A lookahead of one character (pushback buffer)
//   - Special handling for template literals and regex
//   - Error recovery for incremental parsing (IDE scenarios)
//   - Pre-scanning for preparse (lazy compilation)
//
// =============================================================================

#include "js_lexer.hpp"
#include <cctype>
#include <cstring>
#include <cstdlib>
#include <cmath>
#include <unordered_map>

namespace chinstrap {

// =============================================================================
// Token helpers
// =============================================================================

bool Token::is_keyword() const {
    switch (type) {
        case TokenType::Var: case TokenType::Let: case TokenType::Const:
        case TokenType::Function: case TokenType::Return:
        case TokenType::If: case TokenType::Else:
        case TokenType::For: case TokenType::While: case TokenType::Do:
        case TokenType::Break: case TokenType::Continue:
        case TokenType::Switch: case TokenType::Case: case TokenType::Default:
        case TokenType::Class: case TokenType::Extends: case TokenType::Super:
        case TokenType::This: case TokenType::New: case TokenType::Delete:
        case TokenType::Typeof: case TokenType::Instanceof:
        case TokenType::In: case TokenType::Of:
        case TokenType::Try: case TokenType::Catch: case TokenType::Finally:
        case TokenType::Throw:
        case TokenType::Import: case TokenType::Export: case TokenType::From:
        case TokenType::As: case TokenType::Async: case TokenType::Await:
        case TokenType::Yield: case TokenType::Static:
        case TokenType::Get: case TokenType::Set:
        case TokenType::Undefined: case TokenType::Null:
        case TokenType::True: case TokenType::False:
        case TokenType::Void: case TokenType::Debugger:
            return true;
        default:
            return false;
    }
}

std::string Token::type_name() const {
    switch (type) {
        case TokenType::Eof: return "EOF";
        case TokenType::Number: return "Number";
        case TokenType::String: return "String";
        case TokenType::Template: return "Template";
        case TokenType::TemplateStart: return "TemplateStart";
        case TokenType::TemplateMiddle: return "TemplateMiddle";
        case TokenType::TemplateEnd: return "TemplateEnd";
        case TokenType::Regex: return "Regex";
        case TokenType::Identifier: return "Identifier";
        case TokenType::PrivateIdentifier: return "PrivateIdentifier";
        case TokenType::Var: return "var";
        case TokenType::Let: return "let";
        case TokenType::Const: return "const";
        case TokenType::Function: return "function";
        case TokenType::Return: return "return";
        case TokenType::If: return "if";
        case TokenType::Else: return "else";
        case TokenType::For: return "for";
        case TokenType::While: return "while";
        case TokenType::Do: return "do";
        case TokenType::Break: return "break";
        case TokenType::Continue: return "continue";
        case TokenType::Switch: return "switch";
        case TokenType::Case: return "case";
        case TokenType::Default: return "default";
        case TokenType::Class: return "class";
        case TokenType::Extends: return "extends";
        case TokenType::Super: return "super";
        case TokenType::This: return "this";
        case TokenType::New: return "new";
        case TokenType::Delete: return "delete";
        case TokenType::Typeof: return "typeof";
        case TokenType::Instanceof: return "instanceof";
        case TokenType::In: return "in";
        case TokenType::Of: return "of";
        case TokenType::Try: return "try";
        case TokenType::Catch: return "catch";
        case TokenType::Finally: return "finally";
        case TokenType::Throw: return "throw";
        case TokenType::Import: return "import";
        case TokenType::Export: return "export";
        case TokenType::From: return "from";
        case TokenType::As: return "as";
        case TokenType::Async: return "async";
        case TokenType::Await: return "await";
        case TokenType::Yield: return "yield";
        case TokenType::Static: return "static";
        case TokenType::Get: return "get";
        case TokenType::Set: return "set";
        case TokenType::Undefined: return "undefined";
        case TokenType::Null: return "null";
        case TokenType::True: return "true";
        case TokenType::False: return "false";
        case TokenType::Void: return "void";
        case TokenType::Debugger: return "debugger";
        case TokenType::Plus: return "+";
        case TokenType::Minus: return "-";
        case TokenType::Asterisk: return "*";
        case TokenType::Slash: return "/";
        case TokenType::Percent: return "%";
        case TokenType::Exponent: return "**";
        case TokenType::Ampersand: return "&";
        case TokenType::Pipe: return "|";
        case TokenType::Caret: return "^";
        case TokenType::Tilde: return "~";
        case TokenType::LeftShift: return "<<";
        case TokenType::RightShift: return ">>";
        case TokenType::UnsignedRightShift: return ">>>";
        case TokenType::LogicalAnd: return "&&";
        case TokenType::LogicalOr: return "||";
        case TokenType::NullishCoalescing: return "??";
        case TokenType::LessThan: return "<";
        case TokenType::GreaterThan: return ">";
        case TokenType::LessEqual: return "<=";
        case TokenType::GreaterEqual: return ">=";
        case TokenType::Equals: return "==";
        case TokenType::NotEquals: return "!=";
        case TokenType::StrictEquals: return "===";
        case TokenType::StrictNotEquals: return "!==";
        case TokenType::Assign: return "=";
        case TokenType::PlusAssign: return "+=";
        case TokenType::MinusAssign: return "-=";
        case TokenType::MultiplyAssign: return "*=";
        case TokenType::DivideAssign: return "/=";
        case TokenType::PercentAssign: return "%=";
        case TokenType::ExponentAssign: return "**=";
        case TokenType::LeftShiftAssign: return "<<=";
        case TokenType::RightShiftAssign: return ">>=";
        case TokenType::UnsignedRightShiftAssign: return ">>>=";
        case TokenType::BitAndAssign: return "&=";
        case TokenType::BitOrAssign: return "|=";
        case TokenType::BitXorAssign: return "^=";
        case TokenType::LogicalAndAssign: return "&&=";
        case TokenType::LogicalOrAssign: return "||=";
        case TokenType::NullishCoalescingAssign: return "?\?=";
        case TokenType::Increment: return "++";
        case TokenType::Decrement: return "--";
        case TokenType::LParen: return "(";
        case TokenType::RParen: return ")";
        case TokenType::LBrace: return "{";
        case TokenType::RBrace: return "}";
        case TokenType::LBracket: return "[";
        case TokenType::RBracket: return "]";
        case TokenType::Semicolon: return ";";
        case TokenType::Comma: return ",";
        case TokenType::Dot: return ".";
        case TokenType::Spread: return "...";
        case TokenType::OptionalChaining: return "?.";
        case TokenType::Arrow: return "=>";
        case TokenType::Colon: return ":";
        case TokenType::QuestionMark: return "?";
        case TokenType::Hash: return "#";
        case TokenType::Not: return "!";
        case TokenType::Error: return "Error";
    }
    return "Unknown";
}

// =============================================================================
// Lexer implementation
// =============================================================================

Lexer::Lexer(std::string src) : source(std::move(src)) {
    current_token = Token(TokenType::Eof);
}

char Lexer::peek_char(size_t offset) const {
    size_t p = pos + offset;
    if (p >= source.length()) return '\0';
    return source[p];
}

char Lexer::advance_char() {
    if (pos >= source.length()) return '\0';
    char c = source[pos++];
    col++;
    return c;
}

bool Lexer::match_char(char c) {
    if (peek_char() == c) {
        advance_char();
        return true;
    }
    return false;
}

bool Lexer::is_identifier_start(char c) {
    return std::isalpha(static_cast<unsigned char>(c)) || c == '_' || c == '$';
}

bool Lexer::is_identifier_part(char c) {
    return std::isalnum(static_cast<unsigned char>(c)) || c == '_' || c == '$';
}

bool Lexer::is_digit(char c) {
    return c >= '0' && c <= '9';
}

bool Lexer::is_hex_digit(char c) {
    return std::isxdigit(static_cast<unsigned char>(c));
}

bool Lexer::is_octal_digit(char c) {
    return c >= '0' && c <= '7';
}

// =============================================================================
// Keyword lookup
// =============================================================================

TokenType Lexer::keyword_lookup(const std::string& word) {
    // TEACHING NOTE: Keyword Table
    // =============================
    // We use a hash map for keyword lookup. This is O(1) average case.
    // V8 uses a switch on the first character + string comparison, which
    // is faster in practice because it avoids hash computation.
    static const std::unordered_map<std::string, TokenType> keywords = {
        {"var", TokenType::Var},
        {"let", TokenType::Let},
        {"const", TokenType::Const},
        {"function", TokenType::Function},
        {"return", TokenType::Return},
        {"if", TokenType::If},
        {"else", TokenType::Else},
        {"for", TokenType::For},
        {"while", TokenType::While},
        {"do", TokenType::Do},
        {"break", TokenType::Break},
        {"continue", TokenType::Continue},
        {"switch", TokenType::Switch},
        {"case", TokenType::Case},
        {"default", TokenType::Default},
        {"class", TokenType::Class},
        {"extends", TokenType::Extends},
        {"super", TokenType::Super},
        {"this", TokenType::This},
        {"new", TokenType::New},
        {"delete", TokenType::Delete},
        {"typeof", TokenType::Typeof},
        {"instanceof", TokenType::Instanceof},
        {"in", TokenType::In},
        {"of", TokenType::Of},
        {"try", TokenType::Try},
        {"catch", TokenType::Catch},
        {"finally", TokenType::Finally},
        {"throw", TokenType::Throw},
        {"import", TokenType::Import},
        {"export", TokenType::Export},
        {"from", TokenType::From},
        {"as", TokenType::As},
        {"async", TokenType::Async},
        {"await", TokenType::Await},
        {"yield", TokenType::Yield},
        {"static", TokenType::Static},
        {"get", TokenType::Get},
        {"set", TokenType::Set},
        {"undefined", TokenType::Undefined},
        {"null", TokenType::Null},
        {"true", TokenType::True},
        {"false", TokenType::False},
        {"void", TokenType::Void},
        {"debugger", TokenType::Debugger},
    };
    auto it = keywords.find(word);
    if (it != keywords.end()) return it->second;
    return TokenType::Identifier;
}

// =============================================================================
// Skip whitespace and comments
// =============================================================================

void Lexer::skip_whitespace_and_comments() {
    // TEACHING NOTE: Whitespace and Comments
    // =======================================
    // JavaScript whitespace: space, tab, vertical tab, form feed, newline,
    // carriage return, and Unicode whitespace characters.
    //
    // Comments:
    //   - Line comments: // until end of line
    //   - Block comments: /* ... */ (can span multiple lines)
    //
    // HTML comment syntax: <!-- and --> are also recognized as comments in
    // some contexts (for web compatibility). We do not implement this.
    //
    // Newlines are significant for ASI. We track newlines but skip whitespace.

    while (!at_end()) {
        char c = peek_char();
        if (c == ' ' || c == '\t' || c == '\r' || c == '\f' || c == '\v') {
            advance_char();
        } else if (c == '\n') {
            advance_char();
            newline();
        } else if (c == '/' && peek_char(1) == '/') {
            // Line comment
            while (!at_end() && peek_char() != '\n') {
                advance_char();
            }
        } else if (c == '/' && peek_char(1) == '*') {
            // Block comment
            advance_char(); // /
            advance_char(); // *
            while (!at_end()) {
                if (peek_char() == '*' && peek_char(1) == '/') {
                    advance_char(); // *
                    advance_char(); // /
                    break;
                }
                if (peek_char() == '\n') {
                    advance_char();
                    newline();
                } else {
                    advance_char();
                }
            }
        } else {
            break;
        }
    }
}

// =============================================================================
// Scan number
// =============================================================================

Token Lexer::scan_number() {
    // TEACHING NOTE: Number Scanning
    // ===============================
    // JavaScript number literal formats:
    //   - Decimal: 0, 123, 1.5, .5, 1e10, 1.5e-3, 1E10
    //   - Hex: 0xFF, 0Xff
    //   - Binary: 0b1010, 0B1010
    //   - Octal: 0o777, 0O777
    //   - BigInt: 123n (we store as string)
    //   - Legacy octal: 0777 (strict mode forbids this)
    //
    // All numbers are stored as IEEE 754 doubles internally.
    // BigInt support requires arbitrary precision integers, which we do not
    // implement. We store BigInt literals as strings.

    int start_line = line;
    int start_col = col;
    std::string num_str;

    // Check for hex, binary, octal
    if (peek_char() == '0') {
        if (peek_char(1) == 'x' || peek_char(1) == 'X') {
            // Hex
            advance_char(); // 0
            advance_char(); // x
            while (is_hex_digit(peek_char())) {
                num_str += advance_char();
            }
            Token t(TokenType::Number);
            t.number_value = static_cast<double>(std::stoull(num_str, nullptr, 16));
            t.value = "0x" + num_str;
            t.line = start_line;
            t.col = start_col;
            return t;
        } else if (peek_char(1) == 'b' || peek_char(1) == 'B') {
            // Binary
            advance_char(); // 0
            advance_char(); // b
            while (peek_char() == '0' || peek_char() == '1') {
                num_str += advance_char();
            }
            Token t(TokenType::Number);
            t.number_value = static_cast<double>(std::stoull(num_str, nullptr, 2));
            t.value = "0b" + num_str;
            t.line = start_line;
            t.col = start_col;
            return t;
        } else if (peek_char(1) == 'o' || peek_char(1) == 'O') {
            // Octal
            advance_char(); // 0
            advance_char(); // o
            while (is_octal_digit(peek_char())) {
                num_str += advance_char();
            }
            Token t(TokenType::Number);
            t.number_value = static_cast<double>(std::stoull(num_str, nullptr, 8));
            t.value = "0o" + num_str;
            t.line = start_line;
            t.col = start_col;
            return t;
        }
    }

    // Decimal (integer or float)
    while (is_digit(peek_char())) {
        num_str += advance_char();
    }

    // Fractional part
    if (peek_char() == '.' && is_digit(peek_char(1))) {
        num_str += advance_char(); // .
        while (is_digit(peek_char())) {
            num_str += advance_char();
        }
    }

    // Exponent
    if (peek_char() == 'e' || peek_char() == 'E') {
        num_str += advance_char(); // e
        if (peek_char() == '+' || peek_char() == '-') {
            num_str += advance_char();
        }
        while (is_digit(peek_char())) {
            num_str += advance_char();
        }
    }

    // BigInt suffix
    if (peek_char() == 'n') {
        advance_char(); // n
        // Store as number for simplicity (real BigInt not implemented)
        Token t(TokenType::Number);
        t.number_value = static_cast<double>(std::stoll(num_str));
        t.value = num_str + "n";
        t.line = start_line;
        t.col = start_col;
        return t;
    }

    Token t(TokenType::Number);
    try {
        t.number_value = std::stod(num_str);
    } catch (...) {
        t.number_value = std::numeric_limits<double>::quiet_NaN();
    }
    t.value = num_str;
    t.line = start_line;
    t.col = start_col;
    return t;
}

// =============================================================================
// Scan string
// =============================================================================

Token Lexer::scan_string(char quote) {
    // TEACHING NOTE: String Escapes
    // ==============================
    // JavaScript strings support escape sequences:
    //   \n \r \t \v \f \b \0 - control characters
    //   \xHH - hex escape (2 hex digits)
    //   \uHHHH - unicode escape (4 hex digits)
    //   \u{HHHHHH} - extended unicode escape (1-6 hex digits)
    //   \\ \' \" \` - literal characters
    //   \<newline> - line continuation (ignored)
    //
    // V8 decodes escapes during scanning and stores the decoded string.
    // We do the same: the cooked value is the decoded string.

    int start_line = line;
    int start_col = col;
    advance_char(); // consume opening quote

    std::string result;

    while (!at_end() && peek_char() != quote) {
        char c = peek_char();
        if (c == '\n') {
            // JavaScript does not allow raw newlines in string literals
            // (except with \ escape). Line continuation: \<newline>
            errors.push_back({"Unterminated string literal", line, col});
            break;
        }
        if (c == '\\') {
            advance_char(); // backslash
            char esc = advance_char();
            switch (esc) {
                case 'n': result += '\n'; break;
                case 'r': result += '\r'; break;
                case 't': result += '\t'; break;
                case 'v': result += '\v'; break;
                case 'f': result += '\f'; break;
                case 'b': result += '\b'; break;
                case '0': result += '\0'; break;
                case '\\': result += '\\'; break;
                case '\'': result += '\''; break;
                case '"': result += '"'; break;
                case '`': result += '`'; break;
                case '/': result += '/'; break;
                case '\n': newline(); break; // line continuation
                case 'x': {
                    // Hex escape: \xHH
                    std::string hex;
                    for (int i = 0; i < 2 && is_hex_digit(peek_char()); i++) {
                        hex += advance_char();
                    }
                    int val = static_cast<int>(std::stoul(hex, nullptr, 16));
                    if (val < 128) {
                        result += static_cast<char>(val);
                    } else {
                        // Encode as UTF-8
                        if (val < 0x800) {
                            result += static_cast<char>(0xC0 | (val >> 6));
                            result += static_cast<char>(0x80 | (val & 0x3F));
                        } else {
                            result += static_cast<char>(0xE0 | (val >> 12));
                            result += static_cast<char>(0x80 | ((val >> 6) & 0x3F));
                            result += static_cast<char>(0x80 | (val & 0x3F));
                        }
                    }
                    break;
                }
                case 'u': {
                    // Unicode escape: \uHHHH or \u{HHHHHH}
                    if (peek_char() == '{') {
                        advance_char(); // {
                        std::string hex;
                        while (is_hex_digit(peek_char())) {
                            hex += advance_char();
                        }
                        if (peek_char() == '}') advance_char();
                        long val = std::stoul(hex, nullptr, 16);
                        if (val < 0x80) {
                            result += static_cast<char>(val);
                        } else if (val < 0x800) {
                            result += static_cast<char>(0xC0 | (val >> 6));
                            result += static_cast<char>(0x80 | (val & 0x3F));
                        } else if (val < 0x10000) {
                            result += static_cast<char>(0xE0 | (val >> 12));
                            result += static_cast<char>(0x80 | ((val >> 6) & 0x3F));
                            result += static_cast<char>(0x80 | (val & 0x3F));
                        } else if (val < 0x110000) {
                            result += static_cast<char>(0xF0 | (val >> 18));
                            result += static_cast<char>(0x80 | ((val >> 12) & 0x3F));
                            result += static_cast<char>(0x80 | ((val >> 6) & 0x3F));
                            result += static_cast<char>(0x80 | (val & 0x3F));
                        }
                    } else {
                        std::string hex;
                        for (int i = 0; i < 4 && is_hex_digit(peek_char()); i++) {
                            hex += advance_char();
                        }
                        int val = static_cast<int>(std::stoul(hex, nullptr, 16));
                        if (val < 0x80) {
                            result += static_cast<char>(val);
                        } else if (val < 0x800) {
                            result += static_cast<char>(0xC0 | (val >> 6));
                            result += static_cast<char>(0x80 | (val & 0x3F));
                        } else {
                            result += static_cast<char>(0xE0 | (val >> 12));
                            result += static_cast<char>(0x80 | ((val >> 6) & 0x3F));
                            result += static_cast<char>(0x80 | (val & 0x3F));
                        }
                    }
                    break;
                }
                default:
                    // Unknown escape: keep the character literally
                    result += esc;
                    break;
            }
        } else {
            result += advance_char();
        }
    }

    if (peek_char() == quote) {
        advance_char(); // consume closing quote
    } else {
        errors.push_back({"Unterminated string literal", start_line, start_col});
    }

    Token t(TokenType::String);
    t.value = result;
    t.cooked_value = result;
    t.line = start_line;
    t.col = start_col;
    return t;
}

// =============================================================================
// Scan template literal
// =============================================================================

Token Lexer::scan_template(bool start, bool consume_brace) {
    // TEACHING NOTE: Template Literals
    // ==================================
    // Template literals use backticks: `hello world`
    // They support:
    //   - Multi-line strings (newlines are literal)
    //   - Interpolation: `hello ${name}`
    //   - Nesting: `outer ${`inner ${x}`} outer`
    //   - Tagged templates: tag`hello ${name}`
    //
    // Tokenizing templates is complex because of nesting. We need to track:
    //   - TemplateStart: `text ${ - begins a template and an expression
    //   - TemplateMiddle: }text ${ - continues after an expression
    //   - TemplateEnd: }text` - ends a template
    //
    // The lexer scans the string portion, and when it hits ${ it returns
    // a TemplateStart (or TemplateMiddle if we are in the middle). The parser
    // then parses the expression, and calls the lexer again for the next part.

    int start_line = line;
    int start_col = col;
    std::string raw;
    std::string cooked;

    if (start) {
        advance_char(); // consume opening backtick
    } else {
        if (consume_brace) {
            advance_char(); // consume } (from previous ${expr})
        }
        // If consume_brace is false, the } was already consumed by the caller
    }

    while (!at_end()) {
        char c = peek_char();
        if (c == '`') {
            advance_char(); // consume backtick
            Token t(TokenType::TemplateEnd);
            t.value = raw;
            t.cooked_value = cooked;
            t.line = start_line;
            t.col = start_col;
            return t;
        }
        if (c == '$' && peek_char(1) == '{') {
            advance_char(); // $
            advance_char(); // {
            Token t(start ? TokenType::TemplateStart : TokenType::TemplateMiddle);
            t.value = raw;
            t.cooked_value = cooked;
            t.line = start_line;
            t.col = start_col;
            template_depth++;
            template_brace_nesting = 0;
            return t;
        }
        if (c == '\\') {
            advance_char(); // backslash
            char esc = advance_char();
            raw += '\\';
            raw += esc;
            switch (esc) {
                case 'n': cooked += '\n'; break;
                case 'r': cooked += '\r'; break;
                case 't': cooked += '\t'; break;
                case 'v': cooked += '\v'; break;
                case 'f': cooked += '\f'; break;
                case 'b': cooked += '\b'; break;
                case '0': cooked += '\0'; break;
                case '\\': cooked += '\\'; break;
                case '`': cooked += '`'; break;
                case '$': cooked += '$'; break;
                case '\n': cooked += '\n'; newline(); break;
                case 'x': {
                    std::string hex;
                    for (int i = 0; i < 2 && is_hex_digit(peek_char()); i++) {
                        hex += advance_char();
                    }
                    int val = static_cast<int>(std::stoul(hex, nullptr, 16));
                    if (val < 128) cooked += static_cast<char>(val);
                    else {
                        if (val < 0x800) {
                            cooked += static_cast<char>(0xC0 | (val >> 6));
                            cooked += static_cast<char>(0x80 | (val & 0x3F));
                        } else {
                            cooked += static_cast<char>(0xE0 | (val >> 12));
                            cooked += static_cast<char>(0x80 | ((val >> 6) & 0x3F));
                            cooked += static_cast<char>(0x80 | (val & 0x3F));
                        }
                    }
                    break;
                }
                case 'u': {
                    if (peek_char() == '{') {
                        advance_char();
                        std::string hex;
                        while (is_hex_digit(peek_char())) {
                            hex += advance_char();
                        }
                        if (peek_char() == '}') advance_char();
                        long val = std::stoul(hex, nullptr, 16);
                        if (val < 0x80) cooked += static_cast<char>(val);
                        else if (val < 0x800) {
                            cooked += static_cast<char>(0xC0 | (val >> 6));
                            cooked += static_cast<char>(0x80 | (val & 0x3F));
                        } else if (val < 0x10000) {
                            cooked += static_cast<char>(0xE0 | (val >> 12));
                            cooked += static_cast<char>(0x80 | ((val >> 6) & 0x3F));
                            cooked += static_cast<char>(0x80 | (val & 0x3F));
                        } else if (val < 0x110000) {
                            cooked += static_cast<char>(0xF0 | (val >> 18));
                            cooked += static_cast<char>(0x80 | ((val >> 12) & 0x3F));
                            cooked += static_cast<char>(0x80 | ((val >> 6) & 0x3F));
                            cooked += static_cast<char>(0x80 | (val & 0x3F));
                        }
                    } else {
                        std::string hex;
                        for (int i = 0; i < 4 && is_hex_digit(peek_char()); i++) {
                            hex += advance_char();
                        }
                        int val = static_cast<int>(std::stoul(hex, nullptr, 16));
                        if (val < 0x80) cooked += static_cast<char>(val);
                        else if (val < 0x800) {
                            cooked += static_cast<char>(0xC0 | (val >> 6));
                            cooked += static_cast<char>(0x80 | (val & 0x3F));
                        } else {
                            cooked += static_cast<char>(0xE0 | (val >> 12));
                            cooked += static_cast<char>(0x80 | ((val >> 6) & 0x3F));
                            cooked += static_cast<char>(0x80 | (val & 0x3F));
                        }
                    }
                    break;
                }
                default:
                    cooked += esc;
                    break;
            }
        } else if (c == '\n') {
            advance_char();
            newline();
            raw += c;
            cooked += c;
        } else {
            advance_char();
            raw += c;
            cooked += c;
        }
    }

    errors.push_back({"Unterminated template literal", start_line, start_col});
    Token t(TokenType::TemplateEnd);
    t.value = raw;
    t.cooked_value = cooked;
    t.line = start_line;
    t.col = start_col;
    return t;
}

// =============================================================================
// Scan regex literal
// =============================================================================

Token Lexer::scan_regex() {
    // TEACHING NOTE: Regex Tokenization
    // ==================================
    // Regex literals: /pattern/flags
    // The pattern can contain escaped slashes: \/
    // Flags: g (global), i (ignore case), m (multiline), s (dotall),
    //        u (unicode), y (sticky), d (indices)
    //
    // We do not implement a full regex engine. We just tokenize the pattern
    // and flags. The interpreter can store them for later use.

    int start_line = line;
    int start_col = col;
    advance_char(); // consume /

    std::string pattern;
    bool in_class = false; // inside [ ]

    while (!at_end()) {
        char c = peek_char();
        if (c == '\\' && !at_end()) {
            pattern += advance_char();
            if (!at_end()) pattern += advance_char();
            continue;
        }
        if (c == '[') in_class = true;
        if (c == ']') in_class = false;
        if (c == '/' && !in_class) {
            advance_char(); // consume /
            break;
        }
        if (c == '\n') {
            errors.push_back({"Unterminated regex literal", start_line, start_col});
            break;
        }
        pattern += advance_char();
    }

    // Scan flags
    std::string flags;
    while (is_identifier_part(peek_char())) {
        flags += advance_char();
    }

    Token t(TokenType::Regex);
    t.value = pattern;
    t.regex_flags = flags;
    t.line = start_line;
    t.col = start_col;
    return t;
}

// =============================================================================
// Scan identifier or keyword
// =============================================================================

Token Lexer::scan_identifier_or_keyword() {
    int start_line = line;
    int start_col = col;
    std::string name;

    // Handle private identifier (#name)
    bool is_private = false;
    if (peek_char() == '#') {
        is_private = true;
        advance_char();
    }

    while (is_identifier_part(peek_char())) {
        name += advance_char();
    }

    if (is_private) {
        Token t(TokenType::PrivateIdentifier);
        t.value = name;
        t.line = start_line;
        t.col = start_col;
        return t;
    }

    TokenType kw = keyword_lookup(name);
    if (kw != TokenType::Identifier) {
        Token t(kw);
        t.value = name;
        t.line = start_line;
        t.col = start_col;
        return t;
    }

    Token t(TokenType::Identifier);
    t.value = name;
    t.line = start_line;
    t.col = start_col;
    return t;
}

// =============================================================================
// Scan punctuation and operators
// =============================================================================

Token Lexer::scan_punctuation() {
    // TEACHING NOTE: Operator Scanning
    // =================================
    // JavaScript operators can be 1, 2, 3, or 4 characters long.
    // We use "maximal munch" - scan the longest matching operator.
    // For example, >>>= is scanned as one token, not as >>> followed by =.
    //
    // The order of checks matters: we must check longer operators before
    // shorter ones. For example, check === before == and =.

    int start_line = line;
    int start_col = col;
    char c = peek_char();

    // Four-character operators
    if (c == '>' && peek_char(1) == '>' && peek_char(2) == '>' && peek_char(3) == '=') {
        for (int i = 0; i < 4; i++) advance_char();
        Token t(TokenType::UnsignedRightShiftAssign);
        t.line = start_line; t.col = start_col;
        return t;
    }

    // Three-character operators
    if (c == '=' && peek_char(1) == '=' && peek_char(2) == '=') {
        for (int i = 0; i < 3; i++) advance_char();
        Token t(TokenType::StrictEquals); t.line = start_line; t.col = start_col; return t;
    }
    if (c == '!' && peek_char(1) == '=' && peek_char(2) == '=') {
        for (int i = 0; i < 3; i++) advance_char();
        Token t(TokenType::StrictNotEquals); t.line = start_line; t.col = start_col; return t;
    }
    if (c == '>' && peek_char(1) == '>' && peek_char(2) == '>') {
        for (int i = 0; i < 3; i++) advance_char();
        Token t(TokenType::UnsignedRightShift); t.line = start_line; t.col = start_col; return t;
    }
    if (c == '*' && peek_char(1) == '*' && peek_char(2) == '=') {
        for (int i = 0; i < 3; i++) advance_char();
        Token t(TokenType::ExponentAssign); t.line = start_line; t.col = start_col; return t;
    }
    if (c == '.' && peek_char(1) == '.' && peek_char(2) == '.') {
        for (int i = 0; i < 3; i++) advance_char();
        Token t(TokenType::Spread); t.line = start_line; t.col = start_col; return t;
    }
    if (c == '&' && peek_char(1) == '&' && peek_char(2) == '=') {
        for (int i = 0; i < 3; i++) advance_char();
        Token t(TokenType::LogicalAndAssign); t.line = start_line; t.col = start_col; return t;
    }
    if (c == '|' && peek_char(1) == '|' && peek_char(2) == '=') {
        for (int i = 0; i < 3; i++) advance_char();
        Token t(TokenType::LogicalOrAssign); t.line = start_line; t.col = start_col; return t;
    }
    if (c == '?' && peek_char(1) == '?' && peek_char(2) == '=') {
        for (int i = 0; i < 3; i++) advance_char();
        Token t(TokenType::NullishCoalescingAssign); t.line = start_line; t.col = start_col; return t;
    }
    if (c == '<' && peek_char(1) == '<' && peek_char(2) == '=') {
        for (int i = 0; i < 3; i++) advance_char();
        Token t(TokenType::LeftShiftAssign); t.line = start_line; t.col = start_col; return t;
    }
    if (c == '>' && peek_char(1) == '>' && peek_char(2) == '=') {
        for (int i = 0; i < 3; i++) advance_char();
        Token t(TokenType::RightShiftAssign); t.line = start_line; t.col = start_col; return t;
    }

    // Two-character operators
    auto two_char = [this, c](char c1, char c2) -> bool {
        return c == c1 && peek_char(1) == c2;
    };

    if (two_char('+', '+')) { advance_char(); advance_char(); Token t(TokenType::Increment); t.line = start_line; t.col = start_col; return t; }
    if (two_char('-', '-')) { advance_char(); advance_char(); Token t(TokenType::Decrement); t.line = start_line; t.col = start_col; return t; }
    if (two_char('*', '*')) { advance_char(); advance_char(); Token t(TokenType::Exponent); t.line = start_line; t.col = start_col; return t; }
    if (two_char('=', '=')) { advance_char(); advance_char(); Token t(TokenType::Equals); t.line = start_line; t.col = start_col; return t; }
    if (two_char('!', '=')) { advance_char(); advance_char(); Token t(TokenType::NotEquals); t.line = start_line; t.col = start_col; return t; }
    if (two_char('<', '=')) { advance_char(); advance_char(); Token t(TokenType::LessEqual); t.line = start_line; t.col = start_col; return t; }
    if (two_char('>', '=')) { advance_char(); advance_char(); Token t(TokenType::GreaterEqual); t.line = start_line; t.col = start_col; return t; }
    if (two_char('&', '&')) { advance_char(); advance_char(); Token t(TokenType::LogicalAnd); t.line = start_line; t.col = start_col; return t; }
    if (two_char('|', '|')) { advance_char(); advance_char(); Token t(TokenType::LogicalOr); t.line = start_line; t.col = start_col; return t; }
    if (two_char('?', '?')) { advance_char(); advance_char(); Token t(TokenType::NullishCoalescing); t.line = start_line; t.col = start_col; return t; }
    if (two_char('?', '.')) { advance_char(); advance_char(); Token t(TokenType::OptionalChaining); t.line = start_line; t.col = start_col; return t; }
    if (two_char('=', '>')) { advance_char(); advance_char(); Token t(TokenType::Arrow); t.line = start_line; t.col = start_col; return t; }
    if (two_char('<', '<')) { advance_char(); advance_char(); Token t(TokenType::LeftShift); t.line = start_line; t.col = start_col; return t; }
    if (two_char('>', '>')) { advance_char(); advance_char(); Token t(TokenType::RightShift); t.line = start_line; t.col = start_col; return t; }
    if (two_char('+', '=')) { advance_char(); advance_char(); Token t(TokenType::PlusAssign); t.line = start_line; t.col = start_col; return t; }
    if (two_char('-', '=')) { advance_char(); advance_char(); Token t(TokenType::MinusAssign); t.line = start_line; t.col = start_col; return t; }
    if (two_char('*', '=')) { advance_char(); advance_char(); Token t(TokenType::MultiplyAssign); t.line = start_line; t.col = start_col; return t; }
    if (two_char('/', '=')) { advance_char(); advance_char(); Token t(TokenType::DivideAssign); t.line = start_line; t.col = start_col; return t; }
    if (two_char('%', '=')) { advance_char(); advance_char(); Token t(TokenType::PercentAssign); t.line = start_line; t.col = start_col; return t; }
    if (two_char('&', '=')) { advance_char(); advance_char(); Token t(TokenType::BitAndAssign); t.line = start_line; t.col = start_col; return t; }
    if (two_char('|', '=')) { advance_char(); advance_char(); Token t(TokenType::BitOrAssign); t.line = start_line; t.col = start_col; return t; }
    if (two_char('^', '=')) { advance_char(); advance_char(); Token t(TokenType::BitXorAssign); t.line = start_line; t.col = start_col; return t; }

    // Single-character tokens
    advance_char();
    Token t(TokenType::Error);
    t.line = start_line;
    t.col = start_col;
    switch (c) {
        case '+': t = Token(TokenType::Plus); break;
        case '-': t = Token(TokenType::Minus); break;
        case '*': t = Token(TokenType::Asterisk); break;
        case '/': t = Token(TokenType::Slash); break;
        case '%': t = Token(TokenType::Percent); break;
        case '&': t = Token(TokenType::Ampersand); break;
        case '|': t = Token(TokenType::Pipe); break;
        case '^': t = Token(TokenType::Caret); break;
        case '~': t = Token(TokenType::Tilde); break;
        case '=': t = Token(TokenType::Assign); break;
        case '<': t = Token(TokenType::LessThan); break;
        case '>': t = Token(TokenType::GreaterThan); break;
        case '(': t = Token(TokenType::LParen); break;
        case ')': t = Token(TokenType::RParen); break;
        case '{':
            if (template_depth > 0) {
                template_brace_nesting++;
            }
            t = Token(TokenType::LBrace);
            break;
        case '}':
            if (template_depth > 0 && template_brace_nesting == 0) {
                // End of template expression - continue scanning template
                // The } has already been consumed by advance_char() above
                template_depth--;
                Token tok = scan_template(false, false);
                prev_token_was_value = true;
                return tok;
            }
            if (template_depth > 0) {
                template_brace_nesting--;
            }
            t = Token(TokenType::RBrace);
            break;
        case '[': t = Token(TokenType::LBracket); break;
        case ']': t = Token(TokenType::RBracket); break;
        case ';': t = Token(TokenType::Semicolon); break;
        case ',': t = Token(TokenType::Comma); break;
        case '.': t = Token(TokenType::Dot); break;
        case ':': t = Token(TokenType::Colon); break;
        case '?': t = Token(TokenType::QuestionMark); break;
        case '#': t = Token(TokenType::Hash); break;
        case '!': t = Token(TokenType::Not); break;
        default:
            errors.push_back({"Unexpected character: " + std::string(1, c), start_line, start_col});
            t = Token(TokenType::Error);
            t.value = std::string(1, c);
            break;
    }
    return t;
}

// =============================================================================
// Main scan function
// =============================================================================

Token Lexer::scan_token() {
    skip_whitespace_and_comments();

    if (at_end()) {
        Token t(TokenType::Eof);
        t.line = line;
        t.col = col;
        return t;
    }

    char c = peek_char();

    // Numbers
    if (is_digit(c) || (c == '.' && is_digit(peek_char(1)))) {
        Token t = scan_number();
        prev_token_was_value = true;
        return t;
    }

    // Strings
    if (c == '"' || c == '\'') {
        Token t = scan_string(c);
        prev_token_was_value = true;
        return t;
    }

    // Template literals
    if (c == '`') {
        Token t = scan_template(true);
        prev_token_was_value = true;
        return t;
    }

    // Identifiers and keywords
    if (is_identifier_start(c) || c == '#') {
        Token t = scan_identifier_or_keyword();
        // Keywords like true, false, null, this are value-producing
        prev_token_was_value = (t.type == TokenType::True || t.type == TokenType::False ||
                               t.type == TokenType::Null || t.type == TokenType::This ||
                               t.type == TokenType::Undefined || t.type == TokenType::Super ||
                               t.type == TokenType::Identifier);
        return t;
    }

    // Regex vs division
    if (c == '/') {
        if (!prev_token_was_value) {
            // Context suggests regex (after operator, at statement start, etc.)
            Token t = scan_regex();
            prev_token_was_value = true;
            return t;
        }
        // Otherwise it is division - handle in punctuation
    }

    // Punctuation and operators
    Token t = scan_punctuation();
    // Value-producing punctuation: ), ], literal-like tokens
    prev_token_was_value = (t.type == TokenType::RParen || t.type == TokenType::RBracket ||
                            t.type == TokenType::Increment || t.type == TokenType::Decrement);
    return t;
}

// =============================================================================
// Public API: next, peek, peek2
// =============================================================================

Token Lexer::next() {
    if (has_peek2) {
        current_token = peeked2_token;
        peeked2_token = has_peek ? peeked_token : scan_token();
        has_peek = has_peek2; // shift
        has_peek2 = false;
    } else if (has_peek) {
        current_token = peeked_token;
        has_peek = false;
        // peeked2 stays invalid
    } else {
        current_token = scan_token();
    }
    return current_token;
}

Token Lexer::peek() {
    if (!has_peek) {
        peeked_token = scan_token();
        has_peek = true;
    }
    return peeked_token;
}

Token Lexer::peek2() {
    if (!has_peek) {
        peeked_token = scan_token();
        has_peek = true;
    }
    if (!has_peek2) {
        peeked2_token = scan_token();
        has_peek2 = true;
    }
    return peeked2_token;
}

std::string Lexer::get_line(int line_num) const {
    std::string result;
    int current_line = 1;
    for (size_t i = 0; i < source.length(); i++) {
        if (current_line == line_num) {
            while (i < source.length() && source[i] != '\n') {
                result += source[i];
                i++;
            }
            break;
        }
        if (source[i] == '\n') current_line++;
    }
    return result;
}

} // namespace chinstrap